apiVersion: v1
kind: Service
metadata:
  name: rapidcomp-service
  namespace: production
spec:
  type: NodePort
  selector:
    app: rapidcomp
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30007